name: .Net build and test
description: Build and test all .Net projects in working directory

inputs:
  configuration:
    description: "The .Net configuration to use for builds and tests, Debug or Release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: pwsh
      run: |
        $projects = Get-ChildItem -Recurse | Where-Object { $_.Name -like "*.csproj" -and $_.FullName -notlike "*/Examples/*" }
        if ($projects.Count -eq 0) {
          throw "No *.csproj files found"
        }
        $projects | ForEach-Object { dotnet build --configuration ${{ inputs.configuration }}  $_.FullName }

    - name: Test
      shell: pwsh
      run: |
        $projects = Get-ChildItem -Recurse | Where-Object { $_.Name -like "*Tests.csproj" -and $_.FullName -notlike "*/Examples/*" }
        if ($projects.Count -eq 0) {
          throw "No *Tests.csproj files found"
        }
        $projects | ForEach-Object { dotnet test --configuration ${{ inputs.configuration }} --verbosity normal $_.FullName }
