name: .Net build and test
description: Build and test all .Net projects in working directory

inputs:
  configuration:
    description: "The .Net configuration to use for builds and tests, Debug or Release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Include *.csproj -Recurse -Exclude 'Examples\*' | ForEach-Object { dotnet build --configuration ${{ inputs.configuration }}  $_.FullName }

    - name: Test
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Include *Tests.csproj -Recurse -Exclude 'Examples\*' | ForEach-Object { dotnet test --configuration ${{ inputs.configuration }} --verbosity normal $_.FullName }
