name: .Net Publish NuGet package
description: Pack, create a GitHub release, publish to GitHub Packages, publish to NuGet

inputs:
  version:
    description: Semantic version to use for package
    required: true
  csproj-path:
    description: Path to .csproj file
    required: true
  configuration:
    description: The .Net configuration to use for packing, Debug or Release
    default: Release
  save-to-gh-artifact:
    description: If true the NuGet package will be saved to GitHub artifacts
    default: true
  package_name:
    description: The NuGet package name
    required: true
  create_github_release:
    description: If true a GitHub release will be created, with the NuGet package attached
    default: "false"
  github_release_git_tag:
    description: The tag to use for the GitHub release. Required if create_github_release is true
    default: ""
  repository:
    description: The GitHub repository
    required: true
  repository_owner:
    description: The GitHub repository owner
    required: true
  publish_to_github_packages:
    default: "false"
  github_token:
    default: ""
  publish_to_nuget:
    default: ""
  nuget_api_key:
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check github_release_git_tag requirement
      shell: pwsh
      run: |
        if (($env:create_github_release -eq 'true') -and -not $env:github_release_git_tag) {
          Write-Host "github_release_git_tag should be set if create_github_release is true"
          exit 1
        }
      env:
        create_github_release: ${{ inputs.create_github_release }}
        github_release_git_tag: ${{ inputs.github_release_git_tag }}

    - name: Check github_token requirement
      shell: pwsh
      run: |
        if (($env:publish_to_github_packages -eq 'true' -or $env:create_github_release -eq 'true') -and -not $env:github_token) {
          Write-Host "github_token should be set if publish_to_github_packages or create_github_release is true"
          exit 1
        }
      env:
        publish_to_github_packages: ${{ inputs.publish_to_github_packages }}
        create_github_release: ${{ inputs.create_github_release }}
        github_token: ${{ inputs.github_token }}

    - name: Check nuget_api_key requirement
      shell: pwsh
      run: |
        if (($env:publish_to_nuget -eq 'true') -and -not $env:nuget_api_key) {
          Write-Host "nuget_api_key should be set if publish_to_nuget is true"
          exit 1
        }
      env:
        publish_to_nuget: ${{ inputs.publish_to_nuget }}
        nuget_api_key: ${{ inputs.nuget_api_key }}

    - name: Pack project
      shell: pwsh
      run: dotnet pack ./${{ inputs.csproj-path }} --configuration ${{ inputs.configuration }} /p:Version=${{ inputs.version }} --no-restore --no-build --output ./out

    - name: Upload NuGet package to GitHub Artifacts
      if: fromJSON(inputs.save-to-gh-artifact)
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.package_name }}
        path: ./out/${{ inputs.package_name }}.${{ inputs.version }}.nupkg
        if-no-files-found: error

    - name: Create GitHub Release
      if: fromJSON(inputs.create_github_release)
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: pwsh
      run: |
        gh release create ${{ inputs.github_release_git_tag }} --repo ${{ inputs.repository }} --title "${{ inputs.package_name }} v${{ inputs.version }}" --notes "The package ``${{ inputs.package_name }}`` has been released in version ${{ inputs.version }}."

    - name: Upload NuGet package to GitHub Release
      if: fromJSON(inputs.create_github_release)
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: pwsh
      run: |
        gh release upload ${{ inputs.github_release_git_tag }} ./out/${{ inputs.package_name }}.${{ inputs.version }}.nupkg --repo ${{ inputs.repository }}

    - name: Publish to GitHub Packages
      if: fromJSON(inputs.publish_to_github_packages)
      shell: pwsh
      run: dotnet nuget push ./out/${{ inputs.package_name }}.${{ inputs.version }}.nupkg --api-key ${{ inputs.github_token }} --source https://nuget.pkg.github.com/${{ inputs.repository_owner }}/index.json

    - name: Publish to NuGet
      if: fromJSON(inputs.publish_to_nuget)
      shell: pwsh
      run: dotnet nuget push ./out/${{ inputs.package_name }}.${{ inputs.version }}.nupkg --api-key ${{ inputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json
